### ISSUE TITLE
error: package directory 'achievements/templatetags' does not exist 

### ISSUE THREAD

**Issue by ggodik** [ogirardot/django-achievements#1]
building error as follows, running with Python 2.4.3

box:[~/dev/] $ python setup.py install
running install
running build
running build_py
error: package directory 'achievements/templatetags' does not exist

**Comment by ogirardot** [comment]
Hi, sorry i forgot to push it, 
i assumed you took the github source as a base ?
sorry for that. 
Fix has been pushed, tell me if that fixes it properly.

I've added the templatetags directory to the source, i'll be adding template tags to be used soon.
Regards, 

Olivier.

**Comment by ggodik** [comment]
that did the trick , thanks

**Comment by ogirardot** [comment]
thank you for the report :)
if you have any suggestion regarding the docs or features you may need/want
don't hesitate to contribute or just open the corresponding issue :)

2011/11/17 George Godik <
reply@reply.github.com
