### ISSUE TITLE
Add get_user_achievement util method

### ISSUE THREAD

**Issue by ogirardot** [ogirardot/django-achievements#4]
to get all the achievements unlocked by a specific user.

**Comment by markon** [comment]
Implemented here:
1a73eaa0cca96d87bcb46902f6202325f54ddff2

**Comment by ogirardot** [comment]
nice thx, i'll integrate it if you don't mind ?

**Comment by markon** [comment]
Nope, I'm learning how to send you a pull request through github :)

**Comment by ogirardot** [comment]
that would be great :)

**Comment by markon** [comment]
Cool, I've sent the pull request :D

**Comment by ogirardot** [comment]
merged :)

**Comment by ogirardot** [comment]
i updated the AUTHORS file too, 
thx
